trigger:
  branches:
    include:
      - main  # Ensure the correct branch name

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux VM

steps:
  - script: |
      javac Sample.java
      java Sample
    displayName: 'Compile and Run Java Program'
