trigger:
  branches:
    include:
      - main  # Ensure the correct branch name

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux VM

steps:
  steps:
  - script: |
      bash Sample.sh
    displayName: 'Run Sample.txt Script'
