trigger:
  branches:
    include:
      - main  # Runs the pipeline when changes are pushed to 'main'

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux VM

steps:
  - script: |
      sudo apt update
      sudo apt install -y openjdk-11-jdk
      javac Sample.java
      jar -cvf SampleApp.jar *.class
    displayName: 'Compile Java and Create JAR'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
    displayName: 'Publish Build Artifacts'
